version: '3.1'

volumes:
  eduapp_db_data:

services:
  db:
    image: postgres:14
    env_file:
      - ./backend/eduapp_db/postgres.production.env
    volumes:
      - eduapp_db_data:/var/lib/postgresql/data/pgdata
    restart: unless-stopped
  api:
    build:
      context: ./backend/eduapp_db
    image: eduapp/api:latest 
    env_file:
      - ./backend/eduapp_db/production.env
    restart: unless-stopped
    depends_on:
      - db
    links:
      - "db:db"
  nginx:
    build:
      context: .
    image: eduapp/nginx:latest
    extra_hosts:
      - "eduapp.local:0.0.0.0"
      - "admin.local:127.0.0.1"
    ports: 
      - "7979:80"
    # restart: unless-stopped
    depends_on:
      - api