version: '3.1'
services:
  db:
    image: postgres:14
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_USER=postgres
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - eduapp_db_data:/var/lib/postgresql/data/pgdata
    ports:
      - "5433:5432"
  api:
    build:
      context: ./backend/eduapp_db
    image: eduapp_dev/eduapp_api
    depends_on:
      - db
    ports:
      - "3000:3000"
  web:
    build: 
      context: ./frontend
    image: eduapp_dev/eduapp_web
    depends_on: 
      - api
    ports:
      - "3001:3001"
  admin:
    build: 
      context: ./eduapp-administration-panel
    image: eduapp_dev/eduapp_admin
    depends_on:
      - api
    ports:
      - "3002:3002"
volumes:
  eduapp_db_data: