version: '3.1'
services:
  db:
    image: postgres:14
    env_file:
      - ./backend/eduapp_db/postgres.production.env
    volumes:
      - eduapp_db_data:/var/lib/postgresql/data/pgdata
    networks:
      - rails-db
  api:
    build:
      context: ./backend/eduapp_db
    image: eduapp_project:api
    env_file:
      - ./backend/eduapp_db/production.env
    depends_on:
      - db
    networks:
      - rails-db
    ports:
      - "3000:3000"
  web:
    build: 
      context: ./frontend
    image: eduapp_project:web
    env_file:
      - ./frontend/.env
    ports:
      - "3001:3001"
  web_admin:
    build: 
      context: ./eduapp-administration-panel
    image: eduapp_project:admin
    env_file:
      - ./eduapp-administration-panel/.env
    ports:
      - "3002:3002"
volumes:
  eduapp_db_data:

networks:
  rails-db:
    driver: bridge