version: '3.1'

volumes:
  eduapp_db_data:
  nginx_data:

services:
  db:
    image: postgres:14
    env_file:
      - ./backend/eduapp_db/postgres.production.env
    volumes:
      - eduapp_db_data:/var/lib/postgresql/data/pgdata
    restart: unless-stopped
  api:
    build:
      context: ./backend/eduapp_db
    image: eduapp/api:latest 
    env_file:
      - ./backend/eduapp_db/production.env
    restart: unless-stopped
    depends_on:
      - db
    links:
      - "db:db"
  nginx:
    build:
      context: .
    image: eduapp/nginx:latest
    ports: 
      - "8000:80"
    # restart: unless-stopped
    depends_on:
      - api
    volumes:
      - nginx_data:/etc/nginx/conf.d