default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("HOST") { localhost } %>
  port: <%= ENV.fetch("DB_PORT") { 5432 } %>

development:
  <<: *default
  database: eduapp_db_development
  username: <%= ENV.fetch("DEV_DB_USER") { "postgres" } %>
  password: <%= ENV.fetch("DEV_DB_PSWD") { "1234" } %>

test:
  <<: *default
  database: eduapp_db_test
  username: postgres
  password: "1234"

production:
  <<: *default
  database: eduapp_db_production
  username: <%= ENV.fetch("PROD_DB_USER") { "" } %>
  password: <%= ENV.fetch("PROD_DB_PSWD") { "" } %>
  port: <%= ENV.fetch("PROD_DB_PORT") { 5432 } %>
