version: '3.1'
services:
  db:
    image: postgres:14
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_USER=postgres
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - eduapp_db_data:/var/lib/postgresql/data/pgdata
    ports:
      - "5433:5432"
  api:
    build:
      context: .
    image: eduapp/eduapp_db
    depends_on:
      - db
    ports:
      - "3000:3000"
volumes:
  eduapp_db_data: