version: '3.1'
services:
  db:
    image: postgres:14
    env_file:
      - postgres.production.env
    volumes:
      - eduapp_db_data:/var/lib/postgresql/data/pgdata
    ports:
      - "5433:5432"
  api:
    build:
      context: .
    image: eduapp_project:api
    env_file:
      - production.env
    depends_on:
      - db
    ports:
      - "3000:3000"
volumes:
  eduapp_db_data: